### PR TITLE
Tailor deploy targets to cd, sandbox, and demo

### PR DESCRIPTION
**Pull request by bess**

### CODE REVIEW

**Comment by emcaulay** [comment]
out of curiosity, what does "CD" mean in this context?

**Comment by ksclarke** [comment]
I may be way off in my guess, but I'm thinking "continuous deployment" ... what we've thought of in the past as 'test' ... the thing that gets built automatically on changes to GitHub (whereas things to sandbox and demo have to be intentionally pushed there). This is just a guess though. I could be completely wrong.

**Comment by emcaulay** [comment]
@kjallen said he also thought "cd" = "continuous deployment" which is analogous to what I call "dev" ... but with some built in inherent differences. So, if I understand correctly, that means that calling this "server" (is that even a valid word?) "the continuous development" server foregrounds the fact that we're using an automatic deploy process to this server. 

Count this post as part of my general "gatekeeper" role in talking through things I don't understand. Since I'm the product owner, you'll have to train me up on these things because I do think it's important that I understand these words. And even more importantly that I understand the underlying principles that are embedded in these words.

For @bess, can you also verify my understanding? 

Also, please note that having a continuous deployment server is a new thing for UCLA Library (as far as I know). Not that we don't understand it intellectually, but I don't think we have used that process in the past. (Please everyone correct me).

**Comment by ksclarke** [comment]
Just for historical note, we did have a continuous deployment from github to the test VM when we were doing Drupal in-house. The stage and production Jenkins builds were manually triggered but the test build happened on GitHub commit. It was problematic (Drupal often complained) but it was setup and mostly worked.

And cd has been a goal for Sinai, but there have been issues since we do CI and artifact production on Travis. Actually, that would be an interesting thing to learn from DCE. We've not been able to deploy from Travis to a local machine (we put the artifact on S3 and pull from S3 using an in-house Jenkins). DCE seems to be deploying from Travis. Perhaps we can learn how they've gotten around the issues that have held us up. cc: @cachemeoutside

**Pull request merged**
